
name: Build the Prince documentation site
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Build Docusaurus Docs
        run: |
          cd website
          npm install 
          npm run build
      - name: Prepare deployment
        run: |
          cd ./website/build/prince-docs
          rm sitemap.xml doc/*.html
          mv ./index.html ./doc/
          mv doc/doc-install doc/doc-prince doc/doc-refs ./
          cd ./../../..
      - name: Deploy
        uses: nogsantos/ssh-scp-deploy@master
        with:
          src: ./website/build/prince-docs/*
          host: ${{ secrets.SSH_HOST }}
          remote: ${{ secrets.WEB_ROOT }}
          port: ${{ secrets.SSH_PORT }}
          user: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
